repos:
  - repo: "local"
    hooks:
      - id: "itensor-formatter"
        name: "ITensor Pkg Formatter"
        entry: "itpkgfmt ."
        language: "system"
        pass_filenames: false
  - repo: "meta"
    hooks:
      - id: "check-hooks-apply"
      - id: "check-useless-excludes"
