name = "ITensorFormatter"
uuid = "b6bf39f1-c9d3-4bad-aad8-593d802f65fd"
version = "0.2.16"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Runic = "62bfec6d-59d7-401d-8490-b29ee721c001"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
JuliaFormatter = "2.3"
JuliaSyntax = "0.4.10"
Literate = "2.21"
Logging = "1.11"
OrderedCollections = "1.8.1"
PrecompileTools = "1.3.3"
Runic = "1.5.1"
TOML = "1.0.3"
YAML = "0.4.16"
julia = "1.10"


[apps.itfmt]
julia_flags = ["--compile=min", "--optimize=0"]

[apps.itpkgfmt]
julia_flags = ["--compile=min", "--optimize=0"]
submodule = "ITensorPkgFormatter"
